name: format

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # 选择要使用的 node 版本
          node-version: "14"

      - name: Format docs
        run: yarn global add prettier && prettier --write .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Auto format doc
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: format-doc
          delete-branch: true
          title: "[Format doc] Auto format markdown doc"
          assignees: ytvchsy
          reviewers: ytvchsy
